### PR TITLE
Replacing cURL with Guzzle

### PR DESCRIPTION
**Pull request by garnold**
The main issue is the PHP cURL extension used by the SDK doesn't support reading files from streams, which is required when running apps in managed environments like Google App Engine (GAE) which use stream wrappers to provide access to filesystems. This altogether prevents sending signature requests through the SDK for apps running on GAE. Worse, the PHP cURL extension [causes intermittent issues when running on GAE](https://code.google.com/p/googleappengine/issues/detail?id=12451).

We originally worked around this problem by changing our signature requests to use the `file_url` parameter and serving documents from Google Cloud Storage using signed URLs, but unfortunately that doesn't work in development environments.

We then attempted to use [GAE's own cURL "lite" extension](https://cloud.google.com/appengine/docs/php/issue-requests#issuing_an_http_request), but discovered that the extension doesn't support basic authentication with empty passwords, which is an issue when using HelloSign API keys.

I've verified that all functionality we're using from the SDK is still working, however some of the tests fail on unpaid/development accounts.

### CODE REVIEW

**Comment by BHSPitMonkey** [comment]
Thanks for doing this! I am a little hesitant, though, since many of our users don't use Composer to manage dependencies, and wouldn't want to be forced into doing so. I'm not sure this approach provides a viable alternative in those cases.

**Comment by garnold** [comment]
@BHSPitMonkey [It does look like Composer is being used quite a bit to install the SDK](https://packagist.org/packages/hellosign/hellosign-php-sdk), but it's unclear how closely the **installs** metric correlates to your user base.

One solution would be to include the `vendor/` directory in the repo and/or release packages.**\*  We could even [change the name of the `vendor/` directory](https://getcomposer.org/doc/06-config.md#vendor-dir) to avoid conflicts.

What do you think?

**\* On a separate note, the `composer.lock` is currently gitignored but [should be included in the repo](https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file).

**Comment by garnold** [comment]
Hey @BHSPitMonkey, any other thoughts on this pull request?

**Comment by desmondw** [comment]
Hey @garnold, first of all I want to reiterate a thank you for putting in the work on this.

I think we could OK including the vendor folder in this case for the increased support, but only if we're able to drop the PHP requirements of the Guzzle package. The package you committed requires PHP 5.5 whereas we currently only require PHP 5.3. I'm not too familiar with Guzzle but it looks like it's been around for a while - is there a more compatible version you can swap into your commit?

Good catch on the composer.lock as well, would you mind adding that to any updated commit? We'd also prefer it if you removed your contribution from the composer.json since we're only using it in a company capacity (note @BHSPitMonkey and I are not listed there either).

**Comment by garnold** [comment]
Thanks @desmondw !

**Pull request merged**
