### PR TITLE
Add metadata method

### PR DESCRIPTION
**Pull request by jyoung488**

### CODE REVIEW

**Review by radhack — COMMENTED** [review]
Looks good to me

**Review by martinytodorov — CHANGES_REQUESTED** [review]
The method looks good.
Since the metadata is used for other types too, can we move it to the `AbstractResource` class.

**Comment by jyoung488** [comment]
@martinytodorov committed those changes - Alex @radhack is testing it locally

**Comment by jyoung488** [comment]
@martinytodorov tested by @radhack and it works locally

**Review by radhack — APPROVED** [review]
Tested and passed

**Review by martinytodorov — APPROVED** [review]
Looks good.

**Pull request merged**
