### PR TITLE
Fixed OAuth token authentication

### PR DESCRIPTION
**Pull request by schmoove**
Fixes an issue where the "Authorization" header wasn't being set in the REST library when using OAuth tokens, resulting in a "No credentials provided" error on every client request.

The fix involved updating the Comvi\REST library to the latest version, and including its Comvi\CURL dependency.

### CODE REVIEW

**Comment by schmoove** [comment]
Tests will need to be updated to use an OAuth token

**Comment by BHSPitMonkey** [comment]
Thanks for diving into this problem and putting together a fix!

I'm running the unit tests locally and noticing that it looks like file uploads are no longer working under the new REST library, which breaks several key endpoints; I'm going to have to put this on pause until I can find time to look into the issue a bit further. Until then, if your fork is meeting your use case, I'd encourage you to keep using it for the time being until we've figured out how the right way to upstream this change.

**Comment by schmoove** [comment]
Yes I had noticed that too, and was going to spend some time this weekend
debugging it.

Ideally I'd like to propose replacing the Guzzle/REST/CURL libraries
dependencies with a single simple library that can be included in composer, like
this one:

https://github.com/svyatov/CurlWrapper

It's much simpler and a better documented library.

Would you be open to that? I'll swap it out in my work this weekend and see
how it performs.

**Comment by BHSPitMonkey** [comment]
We had some issues in the past related to the cURL extension and I think the direction we were going in was to use something like guzzle instead; What we might do accommodate the non-composer case is to keep using composer for dependencies, and then create a ready-to-use zip/tgz after every release in the Releases section. The main issue is just stabilizing on a HTTP lib that works for us; I'll take a look at CurlWrapper and let you know if we notice any potential snags. Thanks!

**Comment by nrutman** [comment]
It looks like this PR is significantly outdated. Can it be closed?

**Pull request closed without merging**
